Order PAY. logo css fix
paynl/prestashop1.7-plugin pull request #29
Opened 2020-11-18 12:58 UTC by bryantvandenberg

Test op oude versie van Prestashop en nieuwste versie

2020-11-18 13:01 UTC, bryantvandenberg commented
![image](https://user-images.githubusercontent.com/66319215/99533661-83f34400-29a6-11eb-8238-aea4e54c1f62.png)

2020-11-19 12:16 UTC, annevelden approved these changes

2020-11-21 11:01 UTC, woutse requested changes
See Team comments

2020-11-24 13:52 UTC, woutse requested changes
see teams

2020-11-30 10:49 UTC, annevelden approved these changes

2020-12-08 18:09 UTC, woutse approved these changes

2020-12-08 18:10 UTC, merged